// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzsaqtdhaghawttnocgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6c2FxdGRoYWdoYXd0dG5vY2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Nzc3ODEsImV4cCI6MjA2NjQ1Mzc4MX0.iJm67sX8N-jJAwC240hBRrSNwYjvuh-mIkGKGg3vjcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);